// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/unobravo/pulumi-mysql/sdk/go/mysql/internal"
)

var _ = internal.GetEnvOrDefault

func GetAuthenticationPlugin(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:authenticationPlugin")
}
func GetAwsConfigs(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:awsConfigs")
}
func GetAzureConfigs(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:azureConfigs")
}
func GetConnParams(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:connParams")
}
func GetConnectRetryTimeoutSec(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "mysql:connectRetryTimeoutSec")
}
func GetCustomTls(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:customTls")
}
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:endpoint")
}
func GetIamDatabaseAuthentication(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "mysql:iamDatabaseAuthentication")
}
func GetMaxConnLifetimeSec(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "mysql:maxConnLifetimeSec")
}
func GetMaxOpenConns(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "mysql:maxOpenConns")
}
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:password")
}
func GetPrivateIp(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "mysql:privateIp")
}
func GetProxy(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:proxy")
}
func GetTls(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:tls")
}
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:username")
}
