// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mysql
{
    public static class GetDatabases
    {
        /// <summary>
        /// The ``mysql.getDatabases`` gets databases on a MySQL
        /// server.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mysql = Pulumi.Mysql;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var app = Mysql.GetDatabases.Invoke(new()
        ///     {
        ///         Pattern = "test_%",
        ///     });
        /// 
        /// });
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Task<GetDatabasesResult> InvokeAsync(GetDatabasesArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDatabasesResult>("mysql:index/getDatabases:getDatabases", args ?? new GetDatabasesArgs(), options.WithDefaults());

        /// <summary>
        /// The ``mysql.getDatabases`` gets databases on a MySQL
        /// server.
        /// 
        /// ## Example Usage
        /// 
        /// &lt;!--Start PulumiCodeChooser --&gt;
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mysql = Pulumi.Mysql;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var app = Mysql.GetDatabases.Invoke(new()
        ///     {
        ///         Pattern = "test_%",
        ///     });
        /// 
        /// });
        /// ```
        /// &lt;!--End PulumiCodeChooser --&gt;
        /// </summary>
        public static Output<GetDatabasesResult> Invoke(GetDatabasesInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDatabasesResult>("mysql:index/getDatabases:getDatabases", args ?? new GetDatabasesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDatabasesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Patterns for searching databases.
        /// </summary>
        [Input("pattern")]
        public string? Pattern { get; set; }

        public GetDatabasesArgs()
        {
        }
        public static new GetDatabasesArgs Empty => new GetDatabasesArgs();
    }

    public sealed class GetDatabasesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Patterns for searching databases.
        /// </summary>
        [Input("pattern")]
        public Input<string>? Pattern { get; set; }

        public GetDatabasesInvokeArgs()
        {
        }
        public static new GetDatabasesInvokeArgs Empty => new GetDatabasesInvokeArgs();
    }


    [OutputType]
    public sealed class GetDatabasesResult
    {
        /// <summary>
        /// The list of the database names.
        /// </summary>
        public readonly ImmutableArray<string> Databases;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Pattern;

        [OutputConstructor]
        private GetDatabasesResult(
            ImmutableArray<string> databases,

            string id,

            string? pattern)
        {
            Databases = databases;
            Id = id;
            Pattern = pattern;
        }
    }
}
