// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mysql
{
    /// <summary>
    /// The provider type for the mysql package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [MysqlResourceType("pulumi:providers:mysql")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        [Output("authenticationPlugin")]
        public Output<string?> AuthenticationPlugin { get; private set; } = null!;

        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;

        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        [Output("proxy")]
        public Output<string?> Proxy { get; private set; } = null!;

        [Output("tls")]
        public Output<string?> Tls { get; private set; } = null!;

        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs args, CustomResourceOptions? options = null)
            : base("mysql", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("authenticationPlugin")]
        public Input<string>? AuthenticationPlugin { get; set; }

        [Input("awsConfigs", json: true)]
        private InputList<Inputs.ProviderAwsConfigArgs>? _awsConfigs;
        public InputList<Inputs.ProviderAwsConfigArgs> AwsConfigs
        {
            get => _awsConfigs ?? (_awsConfigs = new InputList<Inputs.ProviderAwsConfigArgs>());
            set => _awsConfigs = value;
        }

        [Input("azureConfigs", json: true)]
        private InputList<Inputs.ProviderAzureConfigArgs>? _azureConfigs;
        public InputList<Inputs.ProviderAzureConfigArgs> AzureConfigs
        {
            get => _azureConfigs ?? (_azureConfigs = new InputList<Inputs.ProviderAzureConfigArgs>());
            set => _azureConfigs = value;
        }

        [Input("connParams", json: true)]
        private InputMap<object>? _connParams;
        public InputMap<object> ConnParams
        {
            get => _connParams ?? (_connParams = new InputMap<object>());
            set => _connParams = value;
        }

        [Input("connectRetryTimeoutSec", json: true)]
        public Input<int>? ConnectRetryTimeoutSec { get; set; }

        [Input("customTls", json: true)]
        private InputList<Inputs.ProviderCustomTlArgs>? _customTls;
        public InputList<Inputs.ProviderCustomTlArgs> CustomTls
        {
            get => _customTls ?? (_customTls = new InputList<Inputs.ProviderCustomTlArgs>());
            set => _customTls = value;
        }

        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        [Input("iamDatabaseAuthentication", json: true)]
        public Input<bool>? IamDatabaseAuthentication { get; set; }

        [Input("maxConnLifetimeSec", json: true)]
        public Input<int>? MaxConnLifetimeSec { get; set; }

        [Input("maxOpenConns", json: true)]
        public Input<int>? MaxOpenConns { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("privateIp", json: true)]
        public Input<bool>? PrivateIp { get; set; }

        [Input("proxy")]
        public Input<string>? Proxy { get; set; }

        [Input("tls")]
        public Input<string>? Tls { get; set; }

        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public ProviderArgs()
        {
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
