// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mysql
{
    [MysqlResourceType("mysql:index/sql:Sql")]
    public partial class Sql : global::Pulumi.CustomResource
    {
        [Output("createSql")]
        public Output<string> CreateSql { get; private set; } = null!;

        [Output("deleteSql")]
        public Output<string> DeleteSql { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a Sql resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Sql(string name, SqlArgs args, CustomResourceOptions? options = null)
            : base("mysql:index/sql:Sql", name, args ?? new SqlArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Sql(string name, Input<string> id, SqlState? state = null, CustomResourceOptions? options = null)
            : base("mysql:index/sql:Sql", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Sql resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Sql Get(string name, Input<string> id, SqlState? state = null, CustomResourceOptions? options = null)
        {
            return new Sql(name, id, state, options);
        }
    }

    public sealed class SqlArgs : global::Pulumi.ResourceArgs
    {
        [Input("createSql", required: true)]
        public Input<string> CreateSql { get; set; } = null!;

        [Input("deleteSql", required: true)]
        public Input<string> DeleteSql { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        public SqlArgs()
        {
        }
        public static new SqlArgs Empty => new SqlArgs();
    }

    public sealed class SqlState : global::Pulumi.ResourceArgs
    {
        [Input("createSql")]
        public Input<string>? CreateSql { get; set; }

        [Input("deleteSql")]
        public Input<string>? DeleteSql { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public SqlState()
        {
        }
        public static new SqlState Empty => new SqlState();
    }
}
