// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mysql
{
    /// <summary>
    /// The ``mysql.TiConfig`` resource manages a TiKV or PD variables on a TiDB cluster.
    /// 
    /// &gt; **Note on TiDB:** Possible TiKV or PD variables are available [here](https://docs.pingcap.com/tidb/stable/dynamic-config)
    /// 
    /// &gt; **Note about `destroy`:** `destroy` is trying restore default values as described here.
    ///   Unfortunately not every variable support this.
    /// 
    /// ## Example Usage
    /// 
    /// ### PD
    /// 
    /// &lt;!--Start PulumiCodeChooser --&gt;
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mysql = Pulumi.Mysql;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var logLevel = new Mysql.TiConfig("logLevel", new()
    ///     {
    ///         Type = "pd",
    ///         Value = "warn",
    ///     });
    /// 
    /// });
    /// ```
    /// &lt;!--End PulumiCodeChooser --&gt;
    /// 
    /// ### Set variable for all PD instances
    /// 
    /// &lt;!--Start PulumiCodeChooser --&gt;
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mysql = Pulumi.Mysql;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var logLevel = new Mysql.TiConfig("logLevel", new()
    ///     {
    ///         Type = "pd",
    ///         Value = "warn",
    ///     });
    /// 
    /// });
    /// ```
    /// &lt;!--End PulumiCodeChooser --&gt;
    /// 
    /// ### Set variable for one PD instance only
    /// 
    /// &lt;!--Start PulumiCodeChooser --&gt;
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mysql = Pulumi.Mysql;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var logLevel = new Mysql.TiConfig("logLevel", new()
    ///     {
    ///         Instance = "127.0.0.1:2379",
    ///         Type = "pd",
    ///         Value = "warn",
    ///     });
    /// 
    /// });
    /// ```
    /// &lt;!--End PulumiCodeChooser --&gt;
    /// 
    /// ## TiKV
    /// 
    /// ### Set varibale for all TiKV instances
    /// 
    /// &lt;!--Start PulumiCodeChooser --&gt;
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mysql = Pulumi.Mysql;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var splitQpsThreshold = new Mysql.TiConfig("splitQpsThreshold", new()
    ///     {
    ///         Type = "tikv",
    ///         Value = "100",
    ///     });
    /// 
    /// });
    /// ```
    /// &lt;!--End PulumiCodeChooser --&gt;
    /// 
    /// #### Set variable for one TiKV instance only
    /// 
    /// &lt;!--Start PulumiCodeChooser --&gt;
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mysql = Pulumi.Mysql;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var splitQpsThreshold = new Mysql.TiConfig("splitQpsThreshold", new()
    ///     {
    ///         Instance = "127.0.0.1:20180",
    ///         Type = "tikv",
    ///         Value = "10",
    ///     });
    /// 
    /// });
    /// ```
    /// &lt;!--End PulumiCodeChooser --&gt;
    /// 
    /// ## Import
    /// 
    /// ### Simple example
    /// 
    /// #### TiKV example
    /// 
    /// ```sh
    /// $ pulumi import mysql:index/tiConfig:TiConfig split_qps_threshold' 'tikv#split-qps-threshold'
    /// ```
    /// 
    /// Import value for specific instance
    /// 
    /// ```sh
    /// $ pulumi import mysql:index/tiConfig:TiConfig split_qps_threshold' 'tikv#split-qps-threshold#127.0.0.1:20180'
    /// ```
    /// 
    /// #### PD example
    /// 
    /// ```sh
    /// $ pulumi import mysql:index/tiConfig:TiConfig log_level' 'pd#log.level'
    /// ```
    /// </summary>
    [MysqlResourceType("mysql:index/tiConfig:TiConfig")]
    public partial class TiConfig : global::Pulumi.CustomResource
    {
        [Output("instance")]
        public Output<string?> Instance { get; private set; } = null!;

        /// <summary>
        /// The name of the configuration variable.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The instance type to configure. Possible values are tikv or pd.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// The value of the configuration variable as string.
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a TiConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TiConfig(string name, TiConfigArgs args, CustomResourceOptions? options = null)
            : base("mysql:index/tiConfig:TiConfig", name, args ?? new TiConfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TiConfig(string name, Input<string> id, TiConfigState? state = null, CustomResourceOptions? options = null)
            : base("mysql:index/tiConfig:TiConfig", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TiConfig resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TiConfig Get(string name, Input<string> id, TiConfigState? state = null, CustomResourceOptions? options = null)
        {
            return new TiConfig(name, id, state, options);
        }
    }

    public sealed class TiConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("instance")]
        public Input<string>? Instance { get; set; }

        /// <summary>
        /// The name of the configuration variable.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The instance type to configure. Possible values are tikv or pd.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// The value of the configuration variable as string.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public TiConfigArgs()
        {
        }
        public static new TiConfigArgs Empty => new TiConfigArgs();
    }

    public sealed class TiConfigState : global::Pulumi.ResourceArgs
    {
        [Input("instance")]
        public Input<string>? Instance { get; set; }

        /// <summary>
        /// The name of the configuration variable.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The instance type to configure. Possible values are tikv or pd.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// The value of the configuration variable as string.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public TiConfigState()
        {
        }
        public static new TiConfigState Empty => new TiConfigState();
    }
}
