// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Mysql
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("mysql");

        private static readonly __Value<string?> _authenticationPlugin = new __Value<string?>(() => __config.Get("authenticationPlugin"));
        public static string? AuthenticationPlugin
        {
            get => _authenticationPlugin.Get();
            set => _authenticationPlugin.Set(value);
        }

        private static readonly __Value<ImmutableArray<Pulumi.Mysql.Config.Types.AwsConfigs>> _awsConfigs = new __Value<ImmutableArray<Pulumi.Mysql.Config.Types.AwsConfigs>>(() => __config.GetObject<ImmutableArray<Pulumi.Mysql.Config.Types.AwsConfigs>>("awsConfigs"));
        public static ImmutableArray<Pulumi.Mysql.Config.Types.AwsConfigs> AwsConfigs
        {
            get => _awsConfigs.Get();
            set => _awsConfigs.Set(value);
        }

        private static readonly __Value<ImmutableArray<Pulumi.Mysql.Config.Types.AzureConfigs>> _azureConfigs = new __Value<ImmutableArray<Pulumi.Mysql.Config.Types.AzureConfigs>>(() => __config.GetObject<ImmutableArray<Pulumi.Mysql.Config.Types.AzureConfigs>>("azureConfigs"));
        public static ImmutableArray<Pulumi.Mysql.Config.Types.AzureConfigs> AzureConfigs
        {
            get => _azureConfigs.Get();
            set => _azureConfigs.Set(value);
        }

        private static readonly __Value<ImmutableDictionary<string, object>?> _connParams = new __Value<ImmutableDictionary<string, object>?>(() => __config.GetObject<ImmutableDictionary<string, object>>("connParams"));
        public static ImmutableDictionary<string, object>? ConnParams
        {
            get => _connParams.Get();
            set => _connParams.Set(value);
        }

        private static readonly __Value<int?> _connectRetryTimeoutSec = new __Value<int?>(() => __config.GetInt32("connectRetryTimeoutSec"));
        public static int? ConnectRetryTimeoutSec
        {
            get => _connectRetryTimeoutSec.Get();
            set => _connectRetryTimeoutSec.Set(value);
        }

        private static readonly __Value<ImmutableArray<Pulumi.Mysql.Config.Types.CustomTls>> _customTls = new __Value<ImmutableArray<Pulumi.Mysql.Config.Types.CustomTls>>(() => __config.GetObject<ImmutableArray<Pulumi.Mysql.Config.Types.CustomTls>>("customTls"));
        public static ImmutableArray<Pulumi.Mysql.Config.Types.CustomTls> CustomTls
        {
            get => _customTls.Get();
            set => _customTls.Set(value);
        }

        private static readonly __Value<string?> _endpoint = new __Value<string?>(() => __config.Get("endpoint"));
        public static string? Endpoint
        {
            get => _endpoint.Get();
            set => _endpoint.Set(value);
        }

        private static readonly __Value<bool?> _iamDatabaseAuthentication = new __Value<bool?>(() => __config.GetBoolean("iamDatabaseAuthentication"));
        public static bool? IamDatabaseAuthentication
        {
            get => _iamDatabaseAuthentication.Get();
            set => _iamDatabaseAuthentication.Set(value);
        }

        private static readonly __Value<int?> _maxConnLifetimeSec = new __Value<int?>(() => __config.GetInt32("maxConnLifetimeSec"));
        public static int? MaxConnLifetimeSec
        {
            get => _maxConnLifetimeSec.Get();
            set => _maxConnLifetimeSec.Set(value);
        }

        private static readonly __Value<int?> _maxOpenConns = new __Value<int?>(() => __config.GetInt32("maxOpenConns"));
        public static int? MaxOpenConns
        {
            get => _maxOpenConns.Get();
            set => _maxOpenConns.Set(value);
        }

        private static readonly __Value<string?> _password = new __Value<string?>(() => __config.Get("password"));
        public static string? Password
        {
            get => _password.Get();
            set => _password.Set(value);
        }

        private static readonly __Value<bool?> _privateIp = new __Value<bool?>(() => __config.GetBoolean("privateIp"));
        public static bool? PrivateIp
        {
            get => _privateIp.Get();
            set => _privateIp.Set(value);
        }

        private static readonly __Value<string?> _proxy = new __Value<string?>(() => __config.Get("proxy"));
        public static string? Proxy
        {
            get => _proxy.Get();
            set => _proxy.Set(value);
        }

        private static readonly __Value<string?> _tls = new __Value<string?>(() => __config.Get("tls"));
        public static string? Tls
        {
            get => _tls.Get();
            set => _tls.Set(value);
        }

        private static readonly __Value<string?> _username = new __Value<string?>(() => __config.Get("username"));
        public static string? Username
        {
            get => _username.Get();
            set => _username.Set(value);
        }

        public static class Types
        {

             public class AwsConfigs
             {
                public string? AccessKey { get; set; } = null!;
                public string? Profile { get; set; } = null!;
                public string? Region { get; set; } = null!;
                public string? SecretKey { get; set; } = null!;
            }

             public class AzureConfigs
             {
                public string? ClientId { get; set; } = null!;
                public string? ClientSecret { get; set; } = null!;
                public string? Environment { get; set; } = null!;
                public string? TenantId { get; set; } = null!;
            }

             public class CustomTls
             {
                public string CaCert { get; set; }
                public string ClientCert { get; set; }
                public string ClientKey { get; set; }
                public string? ConfigKey { get; set; } = null!;
            }
        }
    }
}
