# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

authenticationPlugin: Optional[str]

awsConfigs: Optional[str]

azureConfigs: Optional[str]

connParams: Optional[str]

connectRetryTimeoutSec: Optional[int]

customTls: Optional[str]

endpoint: Optional[str]

iamDatabaseAuthentication: Optional[bool]

maxConnLifetimeSec: Optional[int]

maxOpenConns: Optional[int]

password: Optional[str]

privateIp: Optional[bool]

proxy: Optional[str]

tls: Optional[str]

username: Optional[str]

