// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("mysql");

export declare const authenticationPlugin: string | undefined;
Object.defineProperty(exports, "authenticationPlugin", {
    get() {
        return __config.get("authenticationPlugin");
    },
    enumerable: true,
});

export declare const awsConfigs: outputs.config.AwsConfigs[] | undefined;
Object.defineProperty(exports, "awsConfigs", {
    get() {
        return __config.getObject<outputs.config.AwsConfigs[]>("awsConfigs");
    },
    enumerable: true,
});

export declare const azureConfigs: outputs.config.AzureConfigs[] | undefined;
Object.defineProperty(exports, "azureConfigs", {
    get() {
        return __config.getObject<outputs.config.AzureConfigs[]>("azureConfigs");
    },
    enumerable: true,
});

export declare const connParams: {[key: string]: any} | undefined;
Object.defineProperty(exports, "connParams", {
    get() {
        return __config.getObject<{[key: string]: any}>("connParams");
    },
    enumerable: true,
});

export declare const connectRetryTimeoutSec: number | undefined;
Object.defineProperty(exports, "connectRetryTimeoutSec", {
    get() {
        return __config.getObject<number>("connectRetryTimeoutSec");
    },
    enumerable: true,
});

export declare const customTls: outputs.config.CustomTls[] | undefined;
Object.defineProperty(exports, "customTls", {
    get() {
        return __config.getObject<outputs.config.CustomTls[]>("customTls");
    },
    enumerable: true,
});

export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

export declare const iamDatabaseAuthentication: boolean | undefined;
Object.defineProperty(exports, "iamDatabaseAuthentication", {
    get() {
        return __config.getObject<boolean>("iamDatabaseAuthentication");
    },
    enumerable: true,
});

export declare const maxConnLifetimeSec: number | undefined;
Object.defineProperty(exports, "maxConnLifetimeSec", {
    get() {
        return __config.getObject<number>("maxConnLifetimeSec");
    },
    enumerable: true,
});

export declare const maxOpenConns: number | undefined;
Object.defineProperty(exports, "maxOpenConns", {
    get() {
        return __config.getObject<number>("maxOpenConns");
    },
    enumerable: true,
});

export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

export declare const privateIp: boolean | undefined;
Object.defineProperty(exports, "privateIp", {
    get() {
        return __config.getObject<boolean>("privateIp");
    },
    enumerable: true,
});

export declare const proxy: string | undefined;
Object.defineProperty(exports, "proxy", {
    get() {
        return __config.get("proxy");
    },
    enumerable: true,
});

export declare const tls: string | undefined;
Object.defineProperty(exports, "tls", {
    get() {
        return __config.get("tls");
    },
    enumerable: true,
});

export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

