# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .database import *
from .default_roles import *
from .get_databases import *
from .get_tables import *
from .global_variable import *
from .grant import *
from .provider import *
from .rds_config import *
from .role import *
from .sql import *
from .ti_config import *
from .user import *
from .user_password import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_mysql.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_mysql.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "mysql",
  "mod": "index/database",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/database:Database": "Database"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/defaultRoles",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/defaultRoles:DefaultRoles": "DefaultRoles"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/globalVariable",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/globalVariable:GlobalVariable": "GlobalVariable"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/grant",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/grant:Grant": "Grant"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/rdsConfig",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/rdsConfig:RdsConfig": "RdsConfig"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/role",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/role:Role": "Role"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/sql",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/sql:Sql": "Sql"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/tiConfig",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/tiConfig:TiConfig": "TiConfig"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/user",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/user:User": "User"
  }
 },
 {
  "pkg": "mysql",
  "mod": "index/userPassword",
  "fqn": "pulumi_mysql",
  "classes": {
   "mysql:index/userPassword:UserPassword": "UserPassword"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "mysql",
  "token": "pulumi:providers:mysql",
  "fqn": "pulumi_mysql",
  "class": "Provider"
 }
]
"""
)
