# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['TiConfigArgs', 'TiConfig']

@pulumi.input_type
class TiConfigArgs:
    def __init__(__self__, *,
                 type: pulumi.Input[str],
                 value: pulumi.Input[str],
                 instance: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a TiConfig resource.
        :param pulumi.Input[str] type: The instance type to configure. Possible values are tikv or pd.
        :param pulumi.Input[str] value: The value of the configuration variable as string.
        :param pulumi.Input[str] name: The name of the configuration variable.
        """
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)
        if instance is not None:
            pulumi.set(__self__, "instance", instance)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        """
        The instance type to configure. Possible values are tikv or pd.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def value(self) -> pulumi.Input[str]:
        """
        The value of the configuration variable as string.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[str]):
        pulumi.set(self, "value", value)

    @property
    @pulumi.getter
    def instance(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "instance")

    @instance.setter
    def instance(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "instance", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the configuration variable.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _TiConfigState:
    def __init__(__self__, *,
                 instance: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 value: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering TiConfig resources.
        :param pulumi.Input[str] name: The name of the configuration variable.
        :param pulumi.Input[str] type: The instance type to configure. Possible values are tikv or pd.
        :param pulumi.Input[str] value: The value of the configuration variable as string.
        """
        if instance is not None:
            pulumi.set(__self__, "instance", instance)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def instance(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "instance")

    @instance.setter
    def instance(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "instance", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the configuration variable.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[str]]:
        """
        The instance type to configure. Possible values are tikv or pd.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[str]]:
        """
        The value of the configuration variable as string.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "value", value)


class TiConfig(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 instance: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 value: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        The ``TiConfig`` resource manages a TiKV or PD variables on a TiDB cluster.

        > **Note on TiDB:** Possible TiKV or PD variables are available [here](https://docs.pingcap.com/tidb/stable/dynamic-config)

        > **Note about `destroy`:** `destroy` is trying restore default values as described here.
          Unfortunately not every variable support this.

        ## Example Usage

        ### PD

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        log_level = mysql.TiConfig("logLevel",
            type="pd",
            value="warn")
        ```
        <!--End PulumiCodeChooser -->

        ### Set variable for all PD instances

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        log_level = mysql.TiConfig("logLevel",
            type="pd",
            value="warn")
        ```
        <!--End PulumiCodeChooser -->

        ### Set variable for one PD instance only

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        log_level = mysql.TiConfig("logLevel",
            instance="127.0.0.1:2379",
            type="pd",
            value="warn")
        ```
        <!--End PulumiCodeChooser -->

        ## TiKV

        ### Set varibale for all TiKV instances

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        split_qps_threshold = mysql.TiConfig("splitQpsThreshold",
            type="tikv",
            value="100")
        ```
        <!--End PulumiCodeChooser -->

        #### Set variable for one TiKV instance only

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        split_qps_threshold = mysql.TiConfig("splitQpsThreshold",
            instance="127.0.0.1:20180",
            type="tikv",
            value="10")
        ```
        <!--End PulumiCodeChooser -->

        ## Import

        ### Simple example

        #### TiKV example

        ```sh
        $ pulumi import mysql:index/tiConfig:TiConfig split_qps_threshold' 'tikv#split-qps-threshold'
        ```

        Import value for specific instance

        ```sh
        $ pulumi import mysql:index/tiConfig:TiConfig split_qps_threshold' 'tikv#split-qps-threshold#127.0.0.1:20180'
        ```

        #### PD example

        ```sh
        $ pulumi import mysql:index/tiConfig:TiConfig log_level' 'pd#log.level'
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] name: The name of the configuration variable.
        :param pulumi.Input[str] type: The instance type to configure. Possible values are tikv or pd.
        :param pulumi.Input[str] value: The value of the configuration variable as string.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TiConfigArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The ``TiConfig`` resource manages a TiKV or PD variables on a TiDB cluster.

        > **Note on TiDB:** Possible TiKV or PD variables are available [here](https://docs.pingcap.com/tidb/stable/dynamic-config)

        > **Note about `destroy`:** `destroy` is trying restore default values as described here.
          Unfortunately not every variable support this.

        ## Example Usage

        ### PD

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        log_level = mysql.TiConfig("logLevel",
            type="pd",
            value="warn")
        ```
        <!--End PulumiCodeChooser -->

        ### Set variable for all PD instances

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        log_level = mysql.TiConfig("logLevel",
            type="pd",
            value="warn")
        ```
        <!--End PulumiCodeChooser -->

        ### Set variable for one PD instance only

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        log_level = mysql.TiConfig("logLevel",
            instance="127.0.0.1:2379",
            type="pd",
            value="warn")
        ```
        <!--End PulumiCodeChooser -->

        ## TiKV

        ### Set varibale for all TiKV instances

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        split_qps_threshold = mysql.TiConfig("splitQpsThreshold",
            type="tikv",
            value="100")
        ```
        <!--End PulumiCodeChooser -->

        #### Set variable for one TiKV instance only

        <!--Start PulumiCodeChooser -->
        ```python
        import pulumi
        import pulumi_mysql as mysql

        split_qps_threshold = mysql.TiConfig("splitQpsThreshold",
            instance="127.0.0.1:20180",
            type="tikv",
            value="10")
        ```
        <!--End PulumiCodeChooser -->

        ## Import

        ### Simple example

        #### TiKV example

        ```sh
        $ pulumi import mysql:index/tiConfig:TiConfig split_qps_threshold' 'tikv#split-qps-threshold'
        ```

        Import value for specific instance

        ```sh
        $ pulumi import mysql:index/tiConfig:TiConfig split_qps_threshold' 'tikv#split-qps-threshold#127.0.0.1:20180'
        ```

        #### PD example

        ```sh
        $ pulumi import mysql:index/tiConfig:TiConfig log_level' 'pd#log.level'
        ```

        :param str resource_name: The name of the resource.
        :param TiConfigArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TiConfigArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 instance: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 value: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TiConfigArgs.__new__(TiConfigArgs)

            __props__.__dict__["instance"] = instance
            __props__.__dict__["name"] = name
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            if value is None and not opts.urn:
                raise TypeError("Missing required property 'value'")
            __props__.__dict__["value"] = value
        super(TiConfig, __self__).__init__(
            'mysql:index/tiConfig:TiConfig',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            instance: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            type: Optional[pulumi.Input[str]] = None,
            value: Optional[pulumi.Input[str]] = None) -> 'TiConfig':
        """
        Get an existing TiConfig resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] name: The name of the configuration variable.
        :param pulumi.Input[str] type: The instance type to configure. Possible values are tikv or pd.
        :param pulumi.Input[str] value: The value of the configuration variable as string.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _TiConfigState.__new__(_TiConfigState)

        __props__.__dict__["instance"] = instance
        __props__.__dict__["name"] = name
        __props__.__dict__["type"] = type
        __props__.__dict__["value"] = value
        return TiConfig(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def instance(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "instance")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The name of the configuration variable.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def type(self) -> pulumi.Output[str]:
        """
        The instance type to configure. Possible values are tikv or pd.
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def value(self) -> pulumi.Output[str]:
        """
        The value of the configuration variable as string.
        """
        return pulumi.get(self, "value")

