// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface UserAadIdentity {
    identity: string;
    type?: string;
}

export namespace config {
    export interface AwsConfigs {
        accessKey?: string;
        profile?: string;
        region?: string;
        secretKey?: string;
    }

    export interface AzureConfigs {
        clientId?: string;
        clientSecret?: string;
        environment?: string;
        tenantId?: string;
    }

    export interface CustomTls {
        caCert: string;
        clientCert: string;
        clientKey: string;
        configKey?: string;
    }

}
