// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mysql.Inputs
{

    public sealed class ProviderAwsConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKey")]
        public Input<string>? AccessKey { get; set; }

        [Input("profile")]
        public Input<string>? Profile { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("secretKey")]
        public Input<string>? SecretKey { get; set; }

        public ProviderAwsConfigArgs()
        {
        }
        public static new ProviderAwsConfigArgs Empty => new ProviderAwsConfigArgs();
    }
}
