// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mysql.Inputs
{

    public sealed class ProviderCustomTlArgs : global::Pulumi.ResourceArgs
    {
        [Input("caCert", required: true)]
        public Input<string> CaCert { get; set; } = null!;

        [Input("clientCert", required: true)]
        public Input<string> ClientCert { get; set; } = null!;

        [Input("clientKey", required: true)]
        public Input<string> ClientKey { get; set; } = null!;

        [Input("configKey")]
        public Input<string>? ConfigKey { get; set; }

        public ProviderCustomTlArgs()
        {
        }
        public static new ProviderCustomTlArgs Empty => new ProviderCustomTlArgs();
    }
}
